apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ahmedshabana22/gateway:1.1.6
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: rabbitmq-queues-config
            - secretRef:
                name: gateway-secret-key
            - secretRef:
                name: services-keys
            - secretRef:
                name: jwt-secret-key
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: rabbitmq-config
      nodeSelector:
        type: backend
  selector:
    matchLabels:
      app: gateway