scalar ObjectId
scalar Date

type AdminUser {
    username: String!
    password: String!
    roles: [String!]!
    createdAt: Date!
    updatedAt: Date!
    _id: ObjectId!
}

input CreateSystemUserInput {
    username: String!
    password: String!
    roles: [String!]!
}

type Query {
    users: [AdminUser!]!
}

type Mutation {
    createSystemUser(createSystemUserInput: CreateSystemUserInput!): AdminUser!
}
