apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-user
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-user
    spec:
      containers:
        - name: admin-admin-user
          image: ahmedshabana22/admin-user:1.2
          env:
            - name: RMQ_ADMIN_USER_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config-map
                  key: RMQ_ADMIN_USER_QUEUE
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: services-keys
                  key: ADMIN_USER_KEY
            - name: MONGO_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-config-sec
                  key: MONGO_DB_HOST
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-config-sec
                  key: MONGO_DB_NAME
            - name: MONGO_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-config-sec
                  key: MONGO_DB_PORT
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RMQ_USER
            - name: RMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RMQ_PASS
            - name: RMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RMQ_PORT
            - name: RMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RMQ_HOST
      nodeSelector:
        type: backend
  selector:
    matchLabels:
      app: admin-user