apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: rabbitmq-management
  selector:
    app: rabbitmq