scalar JSON
scalar ObjectId
scalar Date

type PaymentTransactionInitiation {
    paymentTransactionId: String!
}

type CheckoutResponse {
    success: Boolean!
}

input CheckoutInput {
    name: String!
    email: String!
    source: String!
    orderId: ObjectId!
    customerId: ObjectId!
}

type Mutation {
    checkout(checkoutInput: CheckoutInput!): CheckoutResponse!
}