apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq
  selector:
    app: rabbitmq